### ISSUE TITLE
[Issue] Clicking Loras adds to Text tab, rather than current tab

### ISSUE THREAD

**Issue by brknsoul** [BinaryQuantumSoul/sdnext-modernui#41]
### Issue Description

Clicking on Loras in the Network pane only adds the <lora> text to the Text tab, at not to the tab currently activated.

### Backend

Chrome (and derivatives)

### Branch

Desktop

### Version Platform Description

```
Python 3.10.11 on Windows
Version: app=sd.next updated=2024-05-06 hash=a6973669 branch=dev
url=https://github.com/vladmandic/automatic/tree/dev
Updating main repository
Upgraded to version: 9ca5e387 Tue May 7 08:45:37 2024 -0400
Platform: arch=AMD64 cpu=Intel64 Family 6 Model 151 Stepping 5, GenuineIntel system=Windows
release=Windows-10-10.0.19045-SP0 python=3.10.11
```

### Relevant log output

```shell
n/a
```

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
with standard ui, extra networks is duplicated 3 times - for text/image/control tabs and only so each duplicated instance can bind to controls on the right tab (e.g. to prompt in txt2img).

with modernui, extra networks is not duplicated and instead binds to first available tab - which by default is control.
but if you enable legacy txt/img interfaces, then it should rebind dynamically and thats a mess. since that is legacy-only, really not sure how much time should be spent on this.

@BinaryQuantumSoul if you know of how to handle this cleanly, please, otherwise this is going to remain and extra networks in legacy mode will be non-functional.

**Comment by BinaryQuantumSoul** [comment]
In modernui, it's actually duplicated three times too: https://github.com/BinaryQuantumSoul/sdnext-modernui/blob/main/html%2Ftemplates%2Faside%2Ftemplate-extra-networks.html

However, I don't know how it binds to prompt and why clicking on the loras in the control one adds to txt2img prompt.

I experience an issue that might be related : EN search box only work in txt2img, and model list refresh too

**Comment by vladmandic** [comment]
ah, this was messy.
multiple issues:
- my extra-networks code caches pages so it doesn't have to rebuild it 3 times for 3 tabs, saves a lot of server-side time. but that means that child elements are wrong so rehosting in modernui doesn't work 100%.
- there is bunch of js code in sdnext which relies on tab detection based on css display setting so needed to emulate that in modernui

anyhow, fixed.
