### ISSUE TITLE
[Issue] Control Tab / Base: Button to reuse the previous seed is missing

### ISSUE THREAD

**Issue by Tillerz** [BinaryQuantumSoul/sdnext-modernui#51]
### Issue Description

Control Tab / Base: Button to reuse the previous seed is missing. See the same button on the txt2img tab.

I tried using the Restore button at the top instead, but that one has MANY problems. Not fetching the seed, deleting the negative prompt, replacing the initial image size with the final initial size and probably a lot more things that are not recovered from "last known generated image" or "current prompt". Whatever restore does, it's not doing what the mouseover says. Probably ONLY loading the things saved via the settings menu.

### Backend

Chrome (and derivatives)

### Branch

Desktop

### Version Platform Description

WSL2, Win11

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by vladmandic** [comment]
Reuse previous seed on control tab has been discussed in sdnext repo, it will not make it as its implementation in txt2img/img2img is horrible.

But restore button should work for control tab. so pls provide exact reproducible examples what doesn't - otherwise it will not going to get fixed. and that issue should go into sdnext repo.
