### ISSUE TITLE
[Issue] In mobile mode, Control checkbox "Input image" gets auto-checked in landscape orientation

### ISSUE THREAD

**Issue by lbeltrame** [BinaryQuantumSoul/sdnext-modernui#62]
### Issue Description

When trying to use Control from Firefox Mobile, I noticed that the "Input image" checkbox gets checked when moving to portrait to landscape mode. In other words:

1. Rotate phone to be in landscape orientation
2. Check "Control" and Uncheck "Input image" if it's checked
3. Rotate the phone in portrait orientation
4. Move back the phone in landscape orientation

The Input image checkbox should be checked after these steps, even if it were unchecked before. This happens every time the orientation changes.

### Backend

Firefox

### Branch

Mobile

### Version Platform Description

Pixel 8, Firefox Mobile.

### Acknowledgements

- [X] I have read the above and searched for existing issues

**Comment by BinaryQuantumSoul** [comment]
This is because you don't have the checkboxes on mobile, instead they are automatically checked when moving to fill the three tabs. https://github.com/BinaryQuantumSoul/sdnext-modernui/blob/bd7937d845bec45e69f97e486905c2d2d72f781f/javascript/sdnext-modernui.js#L118-L119
![image](https://github.com/BinaryQuantumSoul/sdnext-modernui/assets/19613657/a5df80c2-aa9d-4d34-a537-8f404a7eeeff)

When you come back to landscape and exit mobile mode, they were indeed checked.

Still can be fixed though, I was just explaining the reason

**Comment by BinaryQuantumSoul** [comment]
Fixed
